---
title: 'Tales of water and mountains'
date: '2023-12-03'
---

Geography is deterministic. For some, [geography is destiny](https://classics.stanford.edu/publications/geography-destiny-britain-and-world-10000-year-history). For others, [geography is fate](https://storymaps.arcgis.com/stories/1ded8adc781a4821a8bd039ab5551c9f). For Williamsport–a moderately large city situated on the West Branch of the Susquehanna River, as well as the principal cultural, economical, and commercial node of Central Pennsylvania–geography tells the story of of how and why a modest village became the wealthiest place in the world. It illustrates why it was better situated for success than its peers. And finally, it offers an explanation for its decline in the second-half of the 20th century.

> *The first white settlers struggled up the Susquehanna River in the 18th century in search of new farmland. They saw the West Branch Valley as an area of great promise. Their needs were relatively simple, and their ability to utilize the land was limited to what a few individuals and animals could accomplish. Few, if any, thought about the broader geographic character of the region and how it might affect the future of the communities which they were establishing. As more people came into the valley and the nation began to industrialize, that character became increasingly important. In hindsight, it is clear that geography, specifically the mountains and waterways, played a complex and extremely important role in Williamsport’s history. It explains the extent and pattern of the city’s development, the reasons for its great period of prosperity during the lumber era of the late 19th century, and many of the problems it has had, and opportunities it has enjoyed since that time.*

So goes the introductory paragraph in [*Williamsport: Frontier Village to Regional Center*](https://www.google.com/books/edition/Williamsport/o6IpAgAACAAJ?hl=en), authored by Robert H. Larson, Richard J. Morris, and John F. Piper Jr.